name: "github-actions-helm-dependency-updater"
description: "GitHub action to find available updates for Helm dependencies and create a PR to update"
branding:
  color: "green"
  icon: "book-open"
inputs:
  CHART_LOCATION:
    description: "The location of the Chart.yaml file"
    required: true
    type: string
    default: "Chart.yaml"
  UPDATE_ON:
    description: 'A comma separated list of types of version to update on (eg "major,minor,patch")'
    required: true
    type: string
    default: "minor,patch"
  OCI_USERNAME:
    description: "The username for the OCI registry"
    required: true
    type: string
    default: ""
  OCI_PASSWORD:
    description: "The password for the OCI registry"
    required: true
    type: string
    default: ""
  GITHUB_TOKEN:
    description: "The GitHub token to use for creating the PR"
    required: true
    type: string
    default: ""
runs:
  using: "composite"
  steps:
    - name: "Validate OUTPUT_MODE"
      shell: bash
      run: |
        python3 ${{ github.action_path}}/bin/version_validate.py ${{ inputs.UPDATE_ON }}
    - name: Install dependencies
      shell: bash
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r ${{ github.action_path}}/requirements.txt
    - name: "Check for updates"
      id: "check-for-updates"
      shell: bash
      env:
        CHART_LOCATION: ${{ inputs.CHART_LOCATION }}
        UPDATE_ON: ${{ inputs.UPDATE_ON }}
        OCI_USERNAME: ${{ inputs.OCI_USERNAME }}
        OCI_PASSWORD: ${{ inputs.OCI_PASSWORD }}
      run: |
        python3 ${{ github.action_path}}/bin/main.py
    - uses: stefanzweifel/git-auto-commit-action@v4
      id: git-auto-commit
      with:
        commit_message: Updated helm dependencies
        branch: "bump-dependencies"
        create_branch: true
    # GitHub script to create a pull request
    - name: Create Pull Request
      if: steps.git-auto-commit.outputs.changes_detected == 'false'
      uses: actions/github-script@v3
      with:
          github-token: ${{ inputs.GITHUB_TOKEN }}
          script: |
            const title = "chore(release) bump dependencies";
            const body = "chore(release) bump dependencies";
            const head = "bump-dependencies";
            const base = "main";
            const { data: pullRequest } = await github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title,
              body,
              head,
              base,
            });
            core.setOutput("pull-request", pullRequest);
